# Generated by Django 5.2.1 on 2025-06-26 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plandetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('credits', models.IntegerField(default=0)),
                ('duration_days', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plan Detail',
                'verbose_name_plural': 'Plan Details',
                'db_table': 'plan_detail',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('address', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('otp', models.CharField(blank=True, null=True)),
                ('otp_used', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('pending_credits', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice_engine.plandetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice_engine.user')),
            ],
            options={
                'db_table': 'subscription',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='backoffice_engine/user_file')),
                ('resume_text', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice_engine.user')),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.CreateModel(
            name='InterviewResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_questions', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence_level', models.CharField(blank=True, max_length=255, null=True)),
                ('time_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('overall_rating', models.CharField(blank=True, max_length=255, null=True)),
                ('submitted_at', models.CharField(blank=True, max_length=255, null=True)),
                ('final_result', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice_engine.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice_engine.user')),
            ],
            options={
                'db_table': 'interview_result',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice_engine.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice_engine.user')),
            ],
            options={
                'db_table': 'interview',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice_engine.user')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
