# Generated by Django 5.2.1 on 2025-06-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0002_interviewqa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandetail',
            name='credits',
            field=models.IntegerField(default=10),
        ),
        migrations.DeleteModel(
            name='InterviewQA',
        ),
    ]
