# Generated by Django 5.2.1 on 2025-06-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice_engine', '0003_alter_plandetail_credits_delete_interviewqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
